# ==============================================================================
# 🛡️ PRE-COMMIT WORKFLOW CONFIGURATION
# ==============================================================================
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/gitguardian/ggshield
    rev: v1.36.0
    hooks:
      - id: ggshield
        stages: [pre-commit]
